version: '3.4'

services:
  nodejs-hapijs-api-template:
    build:
      context: .
      target: local_dev
      dockerfile: Dockerfile
    container_name: nodejs-hapijs-api-template-local-dev
    volumes:
      # Make sure no `node_modules` directory mounted from host to guest
      - /opt/app/node_modules
      # Make sure no `.tmp` directory mounted from host to guest
      - /opt/app/.tmp
      # Share all project files from host to guest except node_modules that defined above lines
      - ./:/opt/app/
    ports:
      - "3000:3000"
